# Generated by Django 2.1.2 on 2018-12-20 02:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CentroMedico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=50, verbose_name='DESCRIPCION')),
                ('descripcionReducida', models.CharField(blank=True, max_length=5, verbose_name='DESCRIPCION REDUCIDA')),
                ('email', models.EmailField(max_length=254)),
            ],
            options={
                'verbose_name_plural': 'Centros Medicos',
                'ordering': ['descripcion'],
            },
        ),
        migrations.CreateModel(
            name='DatosProfesionales',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matriculap', models.CharField(blank=True, max_length=10, verbose_name='Matricula Provincial')),
                ('matriculan', models.CharField(blank=True, max_length=10, verbose_name='Matricula Nacional')),
                ('email', models.EmailField(max_length=254, verbose_name='Correo Electronico')),
            ],
            options={
                'verbose_name_plural': 'Datos Profesionales',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Domicilio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direccion', models.CharField(max_length=50, verbose_name='DIRECCION')),
                ('observacion', models.TextField(blank=True, verbose_name='OBSERVACION')),
            ],
            options={
                'verbose_name_plural': 'Domicilios',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Especialidad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=50, verbose_name='DESCRIPCION')),
                ('descripcionReducida', models.CharField(blank=True, max_length=5, verbose_name='DESCRIPCION REDUCIDA')),
                ('observacion', models.TextField(blank=True, verbose_name='OBSERVACION')),
            ],
            options={
                'verbose_name_plural': 'Especialidades',
                'ordering': ['descripcion'],
            },
        ),
        migrations.CreateModel(
            name='FactorSanguineo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=1, unique=True)),
            ],
            options={
                'verbose_name': 'factor sanguineo',
                'verbose_name_plural': 'Factores Sanguineos',
                'ordering': ['descripcion'],
            },
        ),
        migrations.CreateModel(
            name='FotoPerfil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(upload_to='fotitos')),
            ],
            options={
                'verbose_name_plural': 'Fotos de Perfil',
            },
        ),
        migrations.CreateModel(
            name='GrupoSanguineo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=2)),
                ('factor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.FactorSanguineo')),
            ],
            options={
                'verbose_name': 'grupo sanguineo',
                'verbose_name_plural': 'Grupos Sanguineos',
                'ordering': ['descripcion'],
            },
        ),
        migrations.CreateModel(
            name='Localidad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=5, verbose_name='CODIGO POSTAL')),
                ('descripcion', models.CharField(max_length=20, verbose_name='DESCRIPCION')),
                ('descripcionReducida', models.CharField(blank=True, max_length=5, null=True, verbose_name='DESCRIPCION REDUCIDA')),
                ('observacion', models.TextField(blank=True, null=True, verbose_name='OBSERVACION')),
            ],
            options={
                'verbose_name_plural': 'Localidades',
                'ordering': ['descripcion'],
            },
        ),
        migrations.CreateModel(
            name='ObraSocial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=100, unique=True)),
                ('descripcion_reducida', models.CharField(max_length=4, unique=True)),
            ],
            options={
                'verbose_name': 'obra social',
                'verbose_name_plural': 'Obras Sociales',
                'ordering': ['descripcion_reducida'],
            },
        ),
        migrations.CreateModel(
            name='ObraSocialDatos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_afiliado', models.CharField(max_length=10, verbose_name='AFILIADO NRO')),
                ('plan', models.CharField(max_length=50, verbose_name='PLAN')),
                ('observacion', models.TextField(blank=True, verbose_name='OBSERVACION')),
                ('obra_social', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.ObraSocial')),
            ],
            options={
                'verbose_name_plural': 'Obras Sociales Datos',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.IntegerField(unique=True, verbose_name='CODIGO')),
                ('codigoAlfa2', models.CharField(max_length=2, verbose_name='COD. 2 LETRAS')),
                ('codigoAlfa3', models.CharField(max_length=3, verbose_name='COD. 3 LETRAS')),
                ('descripcion', models.CharField(max_length=20, verbose_name='DESCRIPCION')),
                ('observacion', models.TextField(blank=True, verbose_name='OBSERVACION')),
            ],
            options={
                'verbose_name_plural': 'Paises',
                'ordering': ['descripcion'],
            },
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='NOMBRE')),
                ('apellido', models.CharField(max_length=100, verbose_name='APELLIDO')),
                ('numero_documento', models.IntegerField(blank=True, null=True)),
                ('fecha_de_nacimiento', models.DateField(verbose_name='FECHA DE NACIMIENTO')),
                ('observacion', models.TextField(blank=True, verbose_name='OBSERVACION')),
                ('datos_profesionales', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='personas', to='core.DatosProfesionales')),
                ('domicilio', models.ManyToManyField(to='core.Domicilio')),
            ],
            options={
                'verbose_name_plural': 'Personas',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Provincia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=4, verbose_name='LETRA DE PROV.')),
                ('descripcion', models.CharField(max_length=20, verbose_name='DESCRIPCION')),
                ('descripcionReducida', models.CharField(max_length=5, null=True, verbose_name='DESCRIPCION REDUCIDA')),
                ('observacion', models.TextField(blank=True, verbose_name='OBSERVACION')),
                ('pais', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.Pais')),
            ],
            options={
                'ordering': ['descripcion'],
            },
        ),
        migrations.CreateModel(
            name='Telefono',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_area', models.CharField(max_length=20, verbose_name='CODIGO DE AREA')),
                ('numero', models.CharField(max_length=20, verbose_name='NUMERO TELEFONICO')),
                ('observacion', models.TextField(blank=True, verbose_name='OBSERVACION')),
            ],
            options={
                'verbose_name_plural': 'Telefonos',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='TipoDocumento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=20, unique=True, verbose_name='DESCRIPCION')),
                ('descripcionReducida', models.CharField(max_length=5, unique=True, verbose_name='DESCRIPCION REDUCIDA')),
                ('observacion', models.TextField(blank=True, verbose_name='OBSERVACION')),
            ],
            options={
                'verbose_name': 'tipo de documento',
                'verbose_name_plural': 'Tipos de documentos',
                'ordering': ['descripcion'],
            },
        ),
        migrations.CreateModel(
            name='TipoDomicilio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=20, unique=True, verbose_name='DESCRIPCION')),
                ('descripcionReducida', models.CharField(max_length=5, unique=True, verbose_name='DESCRIPCION REDUCIDA')),
                ('observacion', models.TextField(blank=True, verbose_name='OBSERVACION')),
            ],
            options={
                'verbose_name': 'tipo de domicilio',
                'verbose_name_plural': 'Tipos de domicilios',
                'ordering': ['descripcion'],
            },
        ),
        migrations.CreateModel(
            name='TipoEstadoCivil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=20, unique=True, verbose_name='DESCRIPCION')),
                ('descripcionReducida', models.CharField(max_length=5, unique=True, verbose_name='DESCRIPCION REDUCIDA')),
                ('observacion', models.TextField(blank=True, verbose_name='OBSERVACION')),
            ],
            options={
                'verbose_name': 'tipo de estado civil',
                'verbose_name_plural': 'Tipos de estado civil',
                'ordering': ['descripcion'],
            },
        ),
        migrations.CreateModel(
            name='TipoSexo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=20, unique=True, verbose_name='DESCRIPCION')),
                ('descripcionReducida', models.CharField(max_length=5, unique=True, verbose_name='DESCRIPCION REDUCIDA')),
                ('observacion', models.TextField(blank=True, verbose_name='OBSERVACION')),
            ],
            options={
                'verbose_name': 'tipo de sexo',
                'verbose_name_plural': 'Tipos de sexo',
                'ordering': ['descripcion'],
            },
        ),
        migrations.CreateModel(
            name='TipoTelefono',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=20, unique=True, verbose_name='DESCRIPCION')),
                ('descripcionReducida', models.CharField(max_length=5, unique=True, verbose_name='DESCRIPCION REDUCIDA')),
                ('observacion', models.TextField(blank=True, verbose_name='OBSERVACION')),
            ],
            options={
                'verbose_name': 'tipo de telefono',
                'verbose_name_plural': 'Tipos de telefono',
                'ordering': ['descripcion'],
            },
        ),
        migrations.CreateModel(
            name='Titulo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=20, unique=True, verbose_name='DESCRIPCION')),
                ('descripcionReducida', models.CharField(blank=True, max_length=5, verbose_name='ALIAS')),
                ('observacion', models.TextField(blank=True, verbose_name='OBSERVACION')),
            ],
            options={
                'verbose_name_plural': 'Titulos',
                'ordering': ['descripcion'],
            },
        ),
        migrations.AddField(
            model_name='telefono',
            name='tipo_telefono',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.TipoTelefono'),
        ),
        migrations.AddField(
            model_name='persona',
            name='estado_civil',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.TipoEstadoCivil'),
        ),
        migrations.AddField(
            model_name='persona',
            name='grupo_sanguineo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.GrupoSanguineo'),
        ),
        migrations.AddField(
            model_name='persona',
            name='localidad_nacimiento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.Localidad'),
        ),
        migrations.AddField(
            model_name='persona',
            name='sexo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.TipoSexo'),
        ),
        migrations.AddField(
            model_name='persona',
            name='telefono',
            field=models.ManyToManyField(to='core.Telefono'),
        ),
        migrations.AddField(
            model_name='persona',
            name='tipo_documento',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='core.TipoDocumento'),
        ),
        migrations.AddField(
            model_name='obrasocialdatos',
            name='persona',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.Persona'),
        ),
        migrations.AddField(
            model_name='localidad',
            name='provincia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.Provincia'),
        ),
        migrations.AddField(
            model_name='fotoperfil',
            name='persona',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.Persona'),
        ),
        migrations.AddField(
            model_name='especialidad',
            name='titulo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.Titulo'),
        ),
        migrations.AddField(
            model_name='domicilio',
            name='localidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.Localidad'),
        ),
        migrations.AddField(
            model_name='domicilio',
            name='tipo_domicilio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.TipoDomicilio'),
        ),
        migrations.AddField(
            model_name='datosprofesionales',
            name='atiende_con',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.ObraSocial'),
        ),
        migrations.AddField(
            model_name='datosprofesionales',
            name='especialidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.Especialidad'),
        ),
        migrations.AddField(
            model_name='centromedico',
            name='domicilio',
            field=models.ManyToManyField(to='core.Domicilio'),
        ),
        migrations.AddField(
            model_name='centromedico',
            name='telefono',
            field=models.ManyToManyField(to='core.Telefono'),
        ),
        migrations.AlterUniqueTogether(
            name='provincia',
            unique_together={('descripcion', 'pais', 'codigo')},
        ),
        migrations.AlterUniqueTogether(
            name='localidad',
            unique_together={('descripcion', 'provincia', 'codigo')},
        ),
        migrations.AlterUniqueTogether(
            name='gruposanguineo',
            unique_together={('descripcion', 'factor')},
        ),
        migrations.AlterUniqueTogether(
            name='especialidad',
            unique_together={('descripcion', 'titulo')},
        ),
    ]
