# Generated by Django 2.1.2 on 2018-11-13 15:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CentroMedico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=50, verbose_name='DESCRIPCION')),
                ('descripcionReducida', models.CharField(blank=True, max_length=5, verbose_name='DESCRIPCION REDUCIDA')),
                ('email', models.EmailField(max_length=254)),
                ('fechaCreacion', models.DateTimeField(auto_now_add=True)),
                ('fechaModificacion', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Centros Medicos',
                'ordering': ['descripcion'],
            },
        ),
        migrations.RemoveField(
            model_name='domicilio',
            name='persona',
        ),
        migrations.RemoveField(
            model_name='telefono',
            name='persona',
        ),
        migrations.AddField(
            model_name='persona',
            name='domicilio',
            field=models.ManyToManyField(to='core.Domicilio'),
        ),
        migrations.AddField(
            model_name='persona',
            name='telefono',
            field=models.ManyToManyField(to='core.Telefono'),
        ),
        migrations.AddField(
            model_name='centromedico',
            name='domicilio',
            field=models.ManyToManyField(to='core.Domicilio'),
        ),
        migrations.AddField(
            model_name='centromedico',
            name='telefono',
            field=models.ManyToManyField(to='core.Telefono'),
        ),
        migrations.AddField(
            model_name='centromedico',
            name='ultimoUsuario',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
