# Generated by Django 2.1.2 on 2018-12-20 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datosprofesionales',
            name='atiende_con',
        ),
        migrations.AddField(
            model_name='datosprofesionales',
            name='atiende_con',
            field=models.ManyToManyField(to='core.ObraSocial'),
        ),
    ]
