# Generated by Django 2.1.2 on 2018-12-24 22:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20181219_2356'),
    ]

    operations = [
        migrations.CreateModel(
            name='CentroMedico_datosProfesionales',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horaEntrada', models.TimeField()),
                ('horaSalida', models.TimeField()),
                ('duracionTurno', models.IntegerField(default=15, verbose_name='Duracion Turno en Minutos')),
                ('centroMedico', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.CentroMedico')),
            ],
        ),
        migrations.CreateModel(
            name='Dias',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.CharField(choices=[('0', 'DOMINGO'), ('1', 'LUNES'), ('2', 'MARTES'), ('3', 'MIERCOLES'), ('4', 'JUEVES'), ('5', 'VIERNES'), ('7', 'SABADO')], max_length=1)),
            ],
            options={
                'verbose_name_plural': 'dias',
            },
        ),
        migrations.AddField(
            model_name='centromedico_datosprofesionales',
            name='dias',
            field=models.ManyToManyField(to='core.Dias'),
        ),
        migrations.AddField(
            model_name='centromedico_datosprofesionales',
            name='persona',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.Persona'),
        ),
    ]
