# Generated by Django 2.1.2 on 2018-12-14 15:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20181120_0915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='datos_profesionales',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='personas', to='core.DatosProfesionales'),
        ),
    ]
