# Generated by Django 2.1.2 on 2018-12-26 13:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20181224_1916'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiasHoras',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.CharField(choices=[('0', 'DOMINGO'), ('1', 'LUNES'), ('2', 'MARTES'), ('3', 'MIERCOLES'), ('4', 'JUEVES'), ('5', 'VIERNES'), ('7', 'SABADO')], max_length=1)),
                ('horaEntrada', models.TimeField()),
                ('horaSalida', models.TimeField()),
                ('duracionTurno', models.IntegerField(default=15, verbose_name='Duracion Turno en Minutos')),
            ],
            options={
                'verbose_name_plural': 'dias',
            },
        ),
        migrations.RemoveField(
            model_name='centromedico_datosprofesionales',
            name='duracionTurno',
        ),
        migrations.RemoveField(
            model_name='centromedico_datosprofesionales',
            name='horaEntrada',
        ),
        migrations.RemoveField(
            model_name='centromedico_datosprofesionales',
            name='horaSalida',
        ),
        migrations.RemoveField(
            model_name='centromedico_datosprofesionales',
            name='dias',
        ),
        migrations.DeleteModel(
            name='Dias',
        ),
        migrations.AddField(
            model_name='centromedico_datosprofesionales',
            name='dias',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='core.DiasHoras'),
        ),
    ]
