# Generated by Django 2.1.2 on 2018-12-28 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20181226_1017'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='centromedico_datosprofesionales',
            name='centroMedico',
        ),
        migrations.RemoveField(
            model_name='centromedico_datosprofesionales',
            name='dias',
        ),
        migrations.RemoveField(
            model_name='centromedico_datosprofesionales',
            name='persona',
        ),
        migrations.DeleteModel(
            name='CentroMedico_datosProfesionales',
        ),
        migrations.DeleteModel(
            name='DiasHoras',
        ),
    ]
