# Generated by Django 2.1.2 on 2018-12-28 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_centromedicopersona_diashoras'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='centromedicopersona',
            name='centroMedico',
        ),
        migrations.RemoveField(
            model_name='centromedicopersona',
            name='persona',
        ),
        migrations.RemoveField(
            model_name='diashoras',
            name='centroMedicoPersona',
        ),
        migrations.AddField(
            model_name='centromedico',
            name='preofesionales',
            field=models.ManyToManyField(to='core.DatosProfesionales'),
        ),
        migrations.DeleteModel(
            name='CentroMedicoPersona',
        ),
        migrations.DeleteModel(
            name='DiasHoras',
        ),
    ]
