# Generated by Django 2.1.2 on 2018-12-28 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20181228_1245'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='centromedico',
            name='preofesionales',
        ),
        migrations.AddField(
            model_name='datosprofesionales',
            name='atiende_en',
            field=models.ManyToManyField(to='core.CentroMedico'),
        ),
    ]
