# Generated by Django 2.1.2 on 2019-01-29 15:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_diashoras'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='diashoras',
            options={'verbose_name_plural': 'dias y horas'},
        ),
        migrations.RemoveField(
            model_name='datosprofesionales',
            name='atiende_en',
        ),
        migrations.AlterField(
            model_name='diashoras',
            name='profesional',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='atiende_en', to='core.DatosProfesionales'),
        ),
    ]
